import Navbar from '@/components/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Grid from '@mui/material/Unstable_Grid2'

const inter = Inter({ subsets: ['latin'] })

export const dynamic = 'auto',
    dynamicParams = true,
    revalidate = 0,
    fetchCache = 'auto',
    runtime = 'nodejs',
    preferredRegion = 'auto';

export const metadata: Metadata = {
  title: 'FrostBytePCs',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Sharp" rel="stylesheet" />
      </head>
      <body className={inter.className}>
        <Grid container sx={{m:1, ml:3}}>
          <Grid xs={2}>
            <Navbar />
          </Grid>
          <Grid xs={10}>
            {children}
          </Grid>
        </Grid>
      </body>
    </html>
  )
}
