import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Sharp" rel="stylesheet" />
        <title>FrostBytePCs</title>
      </head>
      <body className={inter.className}>
        <div className="container">
          <aside>
              <div className="toggle">
                  <div className="logo">
                      <img src="images/logo.png" />
                      <h2>FrostByte<span className="primary">PCs</span></h2>
                  </div>
                  <div className="close" id="close-btn">
                      <span className="material-icons-sharp">
                          close
                      </span>
                  </div>
              </div>

              <div className="sidebar">
                  <a href="#" className="active">
                      <span className="material-icons-sharp">
                          dashboard
                      </span>
                      <h3>Dashboard</h3>
                  </a>
                  <a href="#">
                      <span className="material-icons-sharp">
                          build_circle
                      </span>
                      <h3>Build</h3>
                  </a>
                  <a href="#">
                      <span className="material-icons-sharp">
                          receipt_long
                      </span>
                      <h3>Past Orders</h3>
                  </a>
                  <a href="#">
                      <span className="material-icons-sharp">
                          inventory_2
                      </span>
                      <h3>Inventory</h3>
                  </a>
                  <a href="#">
                      <span className="material-icons-sharp">
                          insights
                      </span>
                      <h3>Analytics</h3>
                  </a>
              </div>
          </aside>
          <main>
          {children}
          </main>
          <div className="right-section">
              <div className="nav">
                  <button id="menu-btn">
                      <span className="material-icons-sharp">
                          menu
                      </span>
                  </button>
                  <div className="dark-mode">
                      <span className="material-icons-sharp active">
                          light_mode
                      </span>
                      <span className="material-icons-sharp">
                          dark_mode
                      </span>
                  </div>

                  <div className="profile">
                      <div className="info">
                          <p>Hey, <b>Sean</b></p>
                          <small className="text-muted">Admin</small>
                      </div>
                      <div className="profile-photo">
                          <img src="images/sean.jpg" />
                      </div>
                  </div>

              </div>

              <div className="user-profile">
                  <div className="logo">
                      <img src="images/sean.jpg" />
                      <h2>Sean Marriott</h2>
                      <p>Fullstack Web Developer</p>
                  </div>
              </div>

              <div className="reminders">
                  <div className="header">
                      <h2>Reminders</h2>
                      <span className="material-icons-sharp">
                          notifications_none
                      </span>
                  </div>

                  <div className="notification">
                      <div className="icon">
                          <span className="material-icons-sharp">
                              handyman
                          </span>
                      </div>
                      <div className="content">
                          <div className="info">
                              <h3>Repair</h3>
                              <small className="text_muted">
                                  08:00 AM - 12:00 PM
                              </small>
                          </div>
                          <span className="material-icons-sharp">
                              more_vert
                          </span>
                      </div>
                  </div>

                  <div className="notification">
                      <div className="icon">
                          <span className="material-icons-sharp">
                              location_on
                          </span>
                      </div>
                      <div className="content">
                          <div className="info">
                              <h3>Pickup</h3>
                              <small className="text_muted">
                                  08:00 AM - 12:00 PM
                              </small>
                          </div>
                          <span className="material-icons-sharp">
                              more_vert
                          </span>
                      </div>
                  </div>

                  <div className="notification add-reminder">
                      <div>
                          <span className="material-icons-sharp">
                              add
                          </span>
                          <h3>Add Reminder</h3>
                      </div>
                  </div>
              </div>
          </div>
      </div>
      </body>
    </html>
  )
}
